// <copyright file="SkuDtoValidator.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Retail.Api.Products.src.CleanArchitecture.Application.Validation
{
    using Retail.Api.Products.src.CleanArchitecture.Application.Dto;
    using Retail.Api.Products.src.CleanArchitecture.Application.Validation.Interfaces;

    /// <summary>
    /// Validates incoming <see cref="SkuDto"/> message.
    /// </summary>
    public class SkuDtoValidator : IMessageValidator<SkuDto>
    {
        private const int MaxNameLength = 100;

        /// <summary>
        /// Validates <see cref="SkuDto"/> message.
        /// </summary>
        /// <param name="message">The message to validate.</param>
        /// <returns>The <see cref="ValidationData"/> to signify if the validation is successful or not.</returns>
        public ValidationData Validate(SkuDto message)
        {
            if (GenericValidator.IsResponseNull(message, nameof(SkuDtoValidator), out var validationData))
            {
                return validationData;
            }

            // For new products, id can be 0 (will be generated by database)
            // But name must be provided and not empty
            if (GenericValidator.IsStringNullOrWhitespace(message.Name ?? string.Empty, nameof(SkuDtoValidator), nameof(message.Name), out validationData))
            {
                return validationData;
            }

            if (!string.IsNullOrWhiteSpace(message.Name) && GenericValidator.ExceedsMaxLength(message.Name, MaxNameLength, nameof(SkuDtoValidator), nameof(message.Name), out validationData))
            {
                return validationData;
            }

            if (GenericValidator.IsLessThanZero(message.UnitPrice, nameof(SkuDtoValidator), nameof(message.UnitPrice), out validationData))
            {
                return validationData;
            }

            if (GenericValidator.IsLessThanZero(message.Inventory, nameof(SkuDtoValidator), nameof(message.Inventory), out validationData))
            {
                return validationData;
            }

            return new ValidationData();
        }
    }
}

