apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-customers-service.fullname" . }}-secrets
  labels:
    {{- include "retail-customers-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | default "YourStrong@Passw0rd" }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | default "guest" }}

