// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retail.Api.Orders.src.CleanArchitecture.Infrastructure.Data;

#nullable disable

namespace Retail.Api.Orders.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retail.Api.Orders.Model.LineItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<long>("SkuId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("LineItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderId = 1L,
                            Qty = 1,
                            SkuId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            OrderId = 1L,
                            Qty = 1,
                            SkuId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            OrderId = 2L,
                            Qty = 1,
                            SkuId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            OrderId = 2L,
                            Qty = 1,
                            SkuId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            OrderId = 3L,
                            Qty = 1,
                            SkuId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            OrderId = 3L,
                            Qty = 1,
                            SkuId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            OrderId = 3L,
                            Qty = 1,
                            SkuId = 3L
                        });
                });

            modelBuilder.Entity("Retail.Api.Orders.Model.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CustomerId = 1L,
                            OrderDate = new DateTime(2023, 3, 9, 13, 15, 21, 206, DateTimeKind.Local).AddTicks(503),
                            TotalAmount = 80.0
                        },
                        new
                        {
                            Id = 2L,
                            CustomerId = 2L,
                            OrderDate = new DateTime(2023, 3, 9, 13, 15, 21, 206, DateTimeKind.Local).AddTicks(515),
                            TotalAmount = 90.0
                        },
                        new
                        {
                            Id = 3L,
                            CustomerId = 3L,
                            OrderDate = new DateTime(2023, 3, 9, 13, 15, 21, 206, DateTimeKind.Local).AddTicks(516),
                            TotalAmount = 140.0
                        });
                });

            modelBuilder.Entity("Retail.Api.Orders.Model.LineItem", b =>
                {
                    b.HasOne("Retail.Api.Orders.Model.Order", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Retail.Api.Orders.Model.Order", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
