// <copyright file="OrderDtoValidator.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Retail.Orders.Write.src.CleanArchitecture.Application.Validation
{
    using Retail.Orders.Write.src.CleanArchitecture.Application.Dto;
    using Retail.Orders.Write.src.CleanArchitecture.Application.Validation.Interfaces;

    /// <summary>
    /// Validates incoming <see cref="OrderDto"/> message.
    /// </summary>
    public class OrderDtoValidator : IMessageValidator<OrderDto>
    {
        /// <summary>
        /// Validates <see cref="OrderDto"/> message.
        /// </summary>
        /// <param name="message">The message to validate.</param>
        /// <returns>The <see cref="ValidationData"/> to signify if the validation is successful or not.</returns>
        public ValidationData Validate(OrderDto message)
        {
            if (GenericValidator.IsResponseNull(message, nameof(OrderDtoValidator), out var validationData))
            {
                return validationData;
            }

            // For new orders, id can be 0 (will be generated by database)
            // But customerId must be greater than 0 (required field)
            if (GenericValidator.HasInvalidRequiredIdentifier(message.CustomerId, nameof(OrderDtoValidator), nameof(message.CustomerId), out validationData))
            {
                return validationData;
            }

            if (message.OrderDate == default(DateTime))
            {
                validationData = new ValidationData(
                    validatorName: nameof(OrderDtoValidator),
                    failureReason: $"The OrderDate field must have a valid date value.");
                return validationData;
            }

            if (message.TotalAmount < 0)
            {
                validationData = new ValidationData(
                    validatorName: nameof(OrderDtoValidator),
                    failureReason: $"The TotalAmount field must be greater than or equal to zero.");
                return validationData;
            }

            return new ValidationData();
        }
    }
}

