using System;
using System.Collections.Generic;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Retail.Orders.Write.src.CleanArchitecture.Application.Dto;
using Retail.Orders.Write.src.CleanArchitecture.Application.Validation;

namespace Retail.Orders.Write.ComponentTests
{
    /// <summary>
    /// Unit tests for OrderDtoValidator class.
    /// </summary>
    [TestClass]
    [TestCategory("UnitTests")]
    public sealed class OrderDtoValidatorTests
    {
        private OrderDtoValidator _validator = null!;

        [TestInitialize]
        public void TestInitialize()
        {
            _validator = new OrderDtoValidator();
        }

        [TestMethod]
        [TestCategory("OrderDtoValidator")]
        public void Validate_WithValidOrderDto_ReturnsValid()
        {
            // Arrange
            var orderDto = new OrderDto
            {
                CustomerId = 100,
                OrderDate = DateTime.Now,
                TotalAmount = 150.00
            };

            // Act
            var result = _validator.Validate(orderDto);

            // Assert
            result.Should().NotBeNull();
            result.IsValid.Should().BeTrue();
        }

        [TestMethod]
        [TestCategory("OrderDtoValidator")]
        public void Validate_WithNullOrderDto_ReturnsInvalid()
        {
            // Act
            var result = _validator.Validate(null!);

            // Assert
            result.Should().NotBeNull();
            result.IsValid.Should().BeFalse();
            result.ValidatorName.Should().Be("OrderDtoValidator");
            result.FailureReason.Should().Contain("null");
        }

        [TestMethod]
        [TestCategory("OrderDtoValidator")]
        public void Validate_WithInvalidCustomerId_ReturnsInvalid()
        {
            // Arrange
            var orderDto = new OrderDto
            {
                CustomerId = 0, // Invalid - must be greater than 0
                OrderDate = DateTime.Now,
                TotalAmount = 150.00
            };

            // Act
            var result = _validator.Validate(orderDto);

            // Assert
            result.Should().NotBeNull();
            result.IsValid.Should().BeFalse();
            result.ValidatorName.Should().Be("OrderDtoValidator");
            result.FailureReason.Should().Contain("CustomerId");
            result.FailureReason.Should().Contain("greater than zero");
        }

        [TestMethod]
        [TestCategory("OrderDtoValidator")]
        public void Validate_WithZeroId_ReturnsValid()
        {
            // Arrange - For new orders, id can be 0 (will be generated by database)
            var orderDto = new OrderDto
            {
                Id = 0, // Valid for new orders
                CustomerId = 100, // Must be greater than 0
                OrderDate = DateTime.Now,
                TotalAmount = 150.00
            };

            // Act
            var result = _validator.Validate(orderDto);

            // Assert
            result.Should().NotBeNull();
            result.IsValid.Should().BeTrue();
        }

        [TestMethod]
        [TestCategory("OrderDtoValidator")]
        public void Validate_WithDefaultOrderDate_ReturnsInvalid()
        {
            // Arrange
            var orderDto = new OrderDto
            {
                CustomerId = 100,
                OrderDate = default(DateTime), // Invalid
                TotalAmount = 150.00
            };

            // Act
            var result = _validator.Validate(orderDto);

            // Assert
            result.Should().NotBeNull();
            result.IsValid.Should().BeFalse();
            result.ValidatorName.Should().Be("OrderDtoValidator");
            result.FailureReason.Should().Contain("OrderDate");
        }

        [TestMethod]
        [TestCategory("OrderDtoValidator")]
        public void Validate_WithNegativeTotalAmount_ReturnsInvalid()
        {
            // Arrange
            var orderDto = new OrderDto
            {
                CustomerId = 100,
                OrderDate = DateTime.Now,
                TotalAmount = -10.00 // Invalid
            };

            // Act
            var result = _validator.Validate(orderDto);

            // Assert
            result.Should().NotBeNull();
            result.IsValid.Should().BeFalse();
            result.ValidatorName.Should().Be("OrderDtoValidator");
            result.FailureReason.Should().Contain("TotalAmount");
        }

        [TestMethod]
        [TestCategory("OrderDtoValidator")]
        public void Validate_WithZeroTotalAmount_ReturnsValid()
        {
            // Arrange
            var orderDto = new OrderDto
            {
                CustomerId = 100,
                OrderDate = DateTime.Now,
                TotalAmount = 0.00 // Valid (zero is allowed)
            };

            // Act
            var result = _validator.Validate(orderDto);

            // Assert
            result.Should().NotBeNull();
            result.IsValid.Should().BeTrue();
        }

        [TestMethod]
        [TestCategory("OrderDtoValidator")]
        public void Validate_WithValidOrderDtoAndLineItems_ReturnsValid()
        {
            // Arrange
            var orderDto = new OrderDto
            {
                CustomerId = 100,
                OrderDate = DateTime.Now,
                TotalAmount = 150.00,
                LineItems = new List<LineItemDto>
                {
                    new LineItemDto { Id = 1, OrderId = 1, SkuId = 100, Qty = 2 }
                }
            };

            // Act
            var result = _validator.Validate(orderDto);

            // Assert
            result.Should().NotBeNull();
            result.IsValid.Should().BeTrue();
        }
    }
}

