// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retail.Api.Products.Data;

#nullable disable

namespace Retail.Api.Products.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230309080007_001")]
    partial class _001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retail.Api.Products.Model.Sku", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Skus");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Rice",
                            UnitPrice = 50.0
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Salt",
                            UnitPrice = 30.0
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Sugar",
                            UnitPrice = 60.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
