// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using InventoryErrorEventNameSpace;
//
//    var inventoryErrorEvent = InventoryErrorEvent.FromJson(jsonString);

namespace InventoryErrorEventNameSpace
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class InventoryErrorEvent
    {
        /// <summary>
        /// Unique identifier of the customer who placed the order
        /// </summary>
        [JsonProperty("customerId")]
        public Guid CustomerId { get; set; }

        /// <summary>
        /// Description of the error that occurred during inventory processing
        /// </summary>
        [JsonProperty("errorMessage", NullValueHandling = NullValueHandling.Ignore)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Date and time when the order was created
        /// </summary>
        [JsonProperty("orderDate")]
        public DateTimeOffset OrderDate { get; set; }

        /// <summary>
        /// Unique identifier of the order
        /// </summary>
        [JsonProperty("orderId")]
        public Guid OrderId { get; set; }

        /// <summary>
        /// Total amount of the order
        /// </summary>
        [JsonProperty("totalAmount")]
        [JsonConverter(typeof(MinMaxValueCheckConverter))]
        public double TotalAmount { get; set; }
    }

    public partial class InventoryErrorEvent
    {
        public static InventoryErrorEvent FromJson(string json) => JsonConvert.DeserializeObject<InventoryErrorEvent>(json, InventoryErrorEventNameSpace.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this InventoryErrorEvent self) => JsonConvert.SerializeObject(self, InventoryErrorEventNameSpace.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class MinMaxValueCheckConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(double) || t == typeof(double?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<double>(reader);
            if (value >= 0)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type double");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (double)untypedValue;
            if (value >= 0)
            {
                serializer.Serialize(writer, value);
                return;
            }
            throw new Exception("Cannot marshal type double");
        }

        public static readonly MinMaxValueCheckConverter Singleton = new MinMaxValueCheckConverter();
    }
}
